/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.sera.android.lemmings;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int control_bash=0x7f020000;
        public static final int control_bash_sel=0x7f020001;
        public static final int control_block=0x7f020002;
        public static final int control_block_sel=0x7f020003;
        public static final int control_build=0x7f020004;
        public static final int control_build_sel=0x7f020005;
        public static final int control_climb=0x7f020006;
        public static final int control_climb_sel=0x7f020007;
        public static final int control_dig=0x7f020008;
        public static final int control_dig_sel=0x7f020009;
        public static final int control_dig_sel_0=0x7f02000a;
        public static final int control_dig_sel_1=0x7f02000b;
        public static final int control_dig_sel_10=0x7f02000c;
        public static final int control_dig_sel_11=0x7f02000d;
        public static final int control_dig_sel_12=0x7f02000e;
        public static final int control_dig_sel_13=0x7f02000f;
        public static final int control_dig_sel_2=0x7f020010;
        public static final int control_dig_sel_3=0x7f020011;
        public static final int control_dig_sel_4=0x7f020012;
        public static final int control_dig_sel_5=0x7f020013;
        public static final int control_dig_sel_6=0x7f020014;
        public static final int control_dig_sel_7=0x7f020015;
        public static final int control_dig_sel_8=0x7f020016;
        public static final int control_dig_sel_9=0x7f020017;
        public static final int control_explode=0x7f020018;
        public static final int control_explode_sel=0x7f020019;
        public static final int control_float=0x7f02001a;
        public static final int control_float_sel=0x7f02001b;
        public static final int control_less=0x7f02001c;
        public static final int control_less_sel=0x7f02001d;
        public static final int control_mine=0x7f02001e;
        public static final int control_mine_sel=0x7f02001f;
        public static final int control_more=0x7f020020;
        public static final int control_more_sel=0x7f020021;
        public static final int control_nuke=0x7f020022;
        public static final int control_nuke_sel=0x7f020023;
        public static final int control_pause=0x7f020024;
        public static final int control_pause_sel=0x7f020025;
        public static final int control_speed=0x7f020026;
        public static final int control_speed_sel=0x7f020027;
        public static final int door0=0x7f020028;
        public static final int door1=0x7f020029;
        public static final int door2=0x7f02002a;
        public static final int door3=0x7f02002b;
        public static final int door4=0x7f02002c;
        public static final int door5=0x7f02002d;
        public static final int door6=0x7f02002e;
        public static final int door7=0x7f02002f;
        public static final int door8=0x7f020030;
        public static final int door9=0x7f020031;
        public static final int door_anim=0x7f020032;
        public static final int exit0=0x7f020033;
        public static final int exit1=0x7f020034;
        public static final int exit2=0x7f020035;
        public static final int exit3=0x7f020036;
        public static final int exit4=0x7f020037;
        public static final int exit5=0x7f020038;
        public static final int exit_anim=0x7f020039;
        public static final int fun=0x7f02003a;
        public static final int fun1=0x7f02003b;
        public static final int hole_basher_l=0x7f02003c;
        public static final int hole_basher_r=0x7f02003d;
        public static final int hole_digger=0x7f02003e;
        public static final int hole_exploder=0x7f02003f;
        public static final int hole_miner_l=0x7f020040;
        public static final int hole_miner_r=0x7f020041;
        public static final int ic_launcher=0x7f020042;
        public static final int lemming_bash_l=0x7f020043;
        public static final int lemming_bash_r=0x7f020044;
        public static final int lemming_block_l=0x7f020045;
        public static final int lemming_block_r=0x7f020046;
        public static final int lemming_build_l=0x7f020047;
        public static final int lemming_build_r=0x7f020048;
        public static final int lemming_climb_l=0x7f020049;
        public static final int lemming_climb_r=0x7f02004a;
        public static final int lemming_climbtop_l=0x7f02004b;
        public static final int lemming_climbtop_r=0x7f02004c;
        public static final int lemming_confused_l=0x7f02004d;
        public static final int lemming_confused_r=0x7f02004e;
        public static final int lemming_dig_l=0x7f02004f;
        public static final int lemming_dig_r=0x7f020050;
        public static final int lemming_drown_s=0x7f020051;
        public static final int lemming_explode_s=0x7f020052;
        public static final int lemming_fall_l=0x7f020053;
        public static final int lemming_fall_r=0x7f020054;
        public static final int lemming_float_l=0x7f020055;
        public static final int lemming_float_r=0x7f020056;
        public static final int lemming_floatstart_l=0x7f020057;
        public static final int lemming_floatstart_r=0x7f020058;
        public static final int lemming_frie_s=0x7f020059;
        public static final int lemming_home_s=0x7f02005a;
        public static final int lemming_left=0x7f02005b;
        public static final int lemming_mine_l=0x7f02005c;
        public static final int lemming_mine_r=0x7f02005d;
        public static final int lemming_right=0x7f02005e;
        public static final int lemming_splut_s=0x7f02005f;
        public static final int lemming_walk_l=0x7f020060;
        public static final int lemming_walk_r=0x7f020061;
        public static final int logo=0x7f020062;
        public static final int mayhem=0x7f020063;
        public static final int progressbar=0x7f020064;
        public static final int scroll_bg=0x7f020065;
        public static final int scroll_bg_sel=0x7f020066;
        public static final int scroll_butt=0x7f020067;
        public static final int scroll_left=0x7f020068;
        public static final int scroll_left_sel=0x7f020069;
        public static final int scroll_right=0x7f02006a;
        public static final int scroll_right_sel=0x7f02006b;
        public static final int target=0x7f02006c;
        public static final int target_left=0x7f02006d;
        public static final int target_right=0x7f02006e;
        public static final int taxing=0x7f02006f;
        public static final int tricky=0x7f020070;
        public static final int vinkje=0x7f020071;
    }
    public static final class id {
        public static final int lemmingsDrawingSurface=0x7f050000;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
    }
}
